swagger: "2.0"
info:
  version: "1.0.0"
  title: "API de Gestion des Transactions"
  description: "API permettant de gérer les transactions"
basePath: "/api/v1"
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: "Bearer Token pour l'authentification."

paths:
  user/transactions:
    get:
      summary: "Obtenir toutes les transactions du mois en cours, groupées par compte"
      description: "Renvoie la liste des transactions du mois en cours, groupées par compte."
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      responses:
        200:
          description: "Succès. Retourne la liste des transactions groupées par compte."
        401:
          description: "Non autorisé. L'utilisateur n'est pas authentifié."
      security:
        - BearerAuth: []  # Requiert une autorisation Bearer Token pour accéder à cette route.

    post:
      summary: "Créer une nouvelle transaction"
      description: "Crée une nouvelle transaction."
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      responses:
        201:
          description: "Créé avec succès. Retourne les détails de la nouvelle transaction."
        401:
          description: "Non autorisé. L'utilisateur n'est pas authentifié."
      security:
        - BearerAuth: []  # Requiert une autorisation Bearer Token pour accéder à cette route.

  user/transactions/{transactionId}:
    get:
      summary: "Obtenir les détails d'une transaction"
      description: "Renvoie les détails d'une transaction spécifique."
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - name: "transactionId"
          in: "path"
          description: "ID de la transaction à récupérer."
          required: true
          type: "string"
      responses:
        200:
          description: "Succès. Retourne les détails de la transaction."
        401:
          description: "Non autorisé. L'utilisateur n'est pas authentifié."
        404:
          description: "Non trouvé. La transaction avec l'ID spécifié n'a pas été trouvée."
      security:
        - BearerAuth: []  # Requiert une autorisation Bearer Token pour accéder à cette route.

    put:
      summary: "Modifier les détails d'une transaction"
      description: "Modifie les détails d'une transaction existante."
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - name: "transactionId"
          in: "path"
          description: "ID de la transaction à modifier."
          required: true
          type: "string"
      responses:
        204:
          description: "Aucun contenu. La transaction a été modifiée avec succès."
        401:
          description: "Non autorisé. L'utilisateur n'est pas authentifié."
        404:
          description: "Non trouvé. La transaction avec l'ID spécifié n'a pas été trouvée."
      security:
        - BearerAuth: []  # Requiert une autorisation Bearer Token pour accéder à cette route.

    delete:
      summary: "Supprimer une transaction"
      description: "Supprime une transaction existante."
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - name: "transactionId"
          in: "path"
          description: "ID de la transaction à supprimer."
          required: true
          type: "string"
      responses:
        204:
          description: "Aucun contenu. La transaction a été supprimée avec succès."
        401:
          description: "Non autorisé. L'utilisateur n'est pas authentifié."
        404:
          description: "Non trouvé. La transaction avec l'ID spécifié n'a pas été trouvée."
      security:
        - BearerAuth: []  # Requiert une autorisation Bearer Token pour accéder à cette route.